defaults:
  tasks_dir: tasks
  trace_dir: traces
judge:
  api_key: dummy
  base_url: http://localhost:46253/v1
  enabled: true
  model_id: gpt-oss-120b
model:
  api_key: dummy
  base_url: http://localhost:56739/v1
  context_window: 32768
  model_id: Qwen/Qwen3-32B
  temperature: 0.0
user_agent_model:
  api_key: dummy
  base_url: http://localhost:46253/v1
  model_id: gpt-oss-120b
